name: PHP 8.4 Upgrade and Auto-Fix

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# Nadajemy uprawnienia do zapisu, aby Rector mógł automatycznie commitować zmiany.
permissions:
  contents: write

jobs:
  # Zadanie 2: Automatyczne poprawki Rectorem i commitowanie
  rector_fix_and_commit:
    name: Auto-Refactoring (Rector)
    runs-on: ubuntu-latest
    
    # To zadanie uruchamiamy tylko na push do głównej gałęzi (nie na PR i nie po Rectora commit)
    if: github.event_name == 'push' && github.event.commits[0].committer.username != 'github-actions[bot]'

    steps:
      - name: Checkout kod
        uses: actions/checkout@v4

      - name: Instalacja PHP i rozszerzeń
        uses: shivammathur/setup-php@v2
        with:
          # Celujemy w najwyższą wersję PHP 8.4
          php-version: 8.4
          # Wymagane rozszerzenia do poprawnego działania Composera (naprawia błąd iconv/mbstring)
          extensions: mbstring, iconv 
          coverage: none

      - name: Buforowanie zależności Composera
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
          

      - name: Instalacja zależności Composera
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Uruchomienie Rectora i refaktoryzacja kodu
        run: ./vendor/bin/rector process

      - name: Automatyczne commitowanie poprawek Rectora
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fix: Automated PHP 8.4 compatibility updates via Rector."
          branch: ${{ github.head_ref || github.ref_name }}
          # Wymuszenie nowego commita, nawet jeśli Rector nic nie zmienił
          push_options: '--force' 
