name: PHP Code Modernization and Upgrade

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  modernize:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Ustawienie PHP 8.4 dla wszystkich narzędzi
    - name: Set up PHP 8.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: json, curl, mbstring, dom, xml
        tools: composer, phpcs

    # 1. Instalacja podstawowych zależności
    - name: Install base dependencies
      run: composer install --no-interaction --prefer-dist

    # 2. Instalacja rozszerzeń specyficznych dla WordPressa
    - name: Install Rector WordPress Extensions (using fsylum)
      run: composer require --dev fsylum/rector-wordpress szepeviktor/phpstan-wordpress --no-scripts
      
    # 3. KRYTYCZNY KROK: Ostateczna aktualizacja i wymuszenie świeżego autoloadera dla Rectora
    # Ten krok gwarantuje, że definicje stałych są widoczne tuż przed uruchomieniem.
    - name: Final Rector Update and Autoloader Rebuild
      run: composer update rector/rector --with-all-dependencies --ignore-platform-reqs

    # 4. Uruchomienie procesu modernizacji (za pomocą jawnego binarium PHP)
    - name: Run Rector
      run: php -d memory_limit=2G vendor/bin/rector process

    # 5. Automatyczny commit i push zmian wprowadzonych przez Rectora
    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'ci: Automatic code modernization (Rector)'
        branch: main