name: PHP Code Modernization and Upgrade

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  modernize:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup PHP 8.4
      - name: Set up PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: json, curl, mbstring, dom, xml
          tools: composer, phpcs

      # 3️⃣ Install base dependencies
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      # 4️⃣ Remove potencjalnie konfliktujące pakiety
      - name: Remove old Rector dependencies
        run: |
          composer remove rector/rector rector/rector-phpunit --dev || true

      # 5️⃣ Install Rector 2.2 + Rector PHPUnit sets + PHPStan 1.12
      - name: Install Rector + PHPStan
        run: |
          composer require --dev rector/rector:^2.2 rector/rector-phpunit:^1.1 -W
          composer require --dev phpstan/phpstan:^1.12 -W

      # 6️⃣ Rebuild Composer autoloader
      - name: Rebuild autoloader
        run: composer dump-autoload -o

      # 7️⃣ Run Rector
      - name: Run Rector
        run: vendor/bin/rector process --config rector.php --ansi --no-progress-bar

      # 8️⃣ Commit & push changes if Rector wprowadzi zmiany
      - name: Commit and Push changes
        id: git-check
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "ci: Rector automatic PHP/WP modernization"
            git push
          else
            echo "No changes from Rector"
          fi
