name: PHP Code Modernization and Upgrade

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  modernize:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup PHP 8.4
      - name: Set up PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: json, curl, mbstring, dom, xml
          tools: composer, phpcs

      # 3️⃣ Install base dependencies
      - name: Install base dependencies
        run: composer install --no-interaction --prefer-dist

      # 4️⃣ Remove old Rector/PHPStan packages (safety)
      - name: Remove old Rector and PHPStan packages
        run: |
          composer remove rector/rector rector/rector-phpunit phpstan/phpstan szepeviktor/phpstan-wordpress --dev || true

      # 5️⃣ Install Rector 2.x + PHPStan 2.x
      - name: Install Rector 2.x and PHPStan 2.x
        run: |
          composer require --dev phpstan/phpstan:^2.1 rector/rector:^2.2 --with-all-dependencies -W

      # 6️⃣ Rebuild Composer autoloader
      - name: Rebuild Composer autoloader
        run: composer dump-autoload -o

      # 7️⃣ Run Rector with custom config
      - name: Run Rector
        run: vendor/bin/rector process --config rector.php --ansi --no-progress-bar

      # 8️⃣ Commit and push changes automatically
      - name: Auto-commit Rector changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: Rector automatic PHP/WP modernization'
          branch: main
