name: PHP Code Modernization and Upgrade

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  modernize:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Ustawienie PHP 8.4
      - name: Set up PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: json, curl, mbstring, dom, xml
          tools: composer, phpcs

      # 3️⃣ Instalacja zależności z lockfile
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      # 4️⃣ Rebuild autoloader (optymalizacja)
      - name: Rebuild Composer autoloader
        run: composer dump-autoload -o

      # 5️⃣ Uruchom Rector z własną konfiguracją
      - name: Run Rector
        run: vendor/bin/rector process --config rector.php --ansi --no-progress-bar

      # 6️⃣ Automatyczny commit i push zmian
      - name: Commit and Push Rector changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: Rector automatic PHP/WP modernization'
          branch: main
          file_pattern: '**/*.php'
